

###
get http://localhost:3000/bicycle/1

### POST
post http://localhost:3000/bicycle
Content-Type: "application/json"

{
    "data":{
        "brand" : "el perro",
        "color" : "perron"
    }
}

###
put http://localhost:3000/bicycle/x
Content-Type: "application/json"

{
    "data":{
        "brand" : "soy otro",
        "color" : "perrititito"
    }
}

###
delete http://localhost:3000/bicycle/1

###
post http://localhost:3000/bicycle/99/update
Content-Type: "application/json"

{
    "data":{
        "brand" : "soy otro",
        "color" : "perritititxo"
    }
}

###
get http://localhost:3000/bicycle/99


###
# post  http://localhost:3000/bicycle
post  http://localhost:3000/
Content-Type: application/application/json

{
    "data":{
        "queso":"de perro",
        "quesote":"no"
    }
}

###
get http://localhost:3000/bicycle/1