###
get http://localhost:3000/2


###post
post http://localhost:3000
Content-Type: application/json

{
    "data":{
        "brand":"brandon",
        "color":"coloron",
        "aaa":"aaa"
    }
}

###put
put http://localhost:3000/2
Content-Type: application/json

{
    "data":{
        "brand":"brandonPP",
        "color":"coloronPP",
        "aaa":"aaaPP"
    }
}


###deelete
delete http://localhost:3000/2
